name: Hello World

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  Hello-World-Job:
    runs-on:
      - codebuild--${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
