name: automated publishing to docker
name: Mixed inputs

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review
    inputs:
      ecr_repo:
        description: amazon ECR repo of choice
        required: true

jobs:
    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.ecr_repo }}"
