name: test_workflow 

on:
  workflow_call:
    inputs:
      username:
        description: 'amazon repo name'
        default: 'john-doe'
        required: true
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
